### ISSUE TITLE
Full screen is not correct

### ISSUE THREAD

**Issue by Amiralgaby** [migechal/Boxing2D#1]
On my side the full screen only shows the top of the scene, I didn't get the menu either I think.
Good luck for this project

**Comment by migechal** [comment]
Thank you for this issue! I completely forgot about this project, I'll try and continue it in my spare time :)

**Comment by Amiralgaby** [comment]
Your welcome for the issue.
Don't force yourself to do anything if you've given up on it, it's not a big deal.
You probably have other good things to do in your spare time.

**Comment by migechal** [comment]
If you look into the dev branch you will see the version which should fix the issue, it's not entirely done but it will be soon.

**Comment by Amiralgaby** [comment]
Hi,
I make the game once again, the window appear good :)
